### ISSUE TITLE
TableMeta ，How did you deal with it?

### ISSUE THREAD

**Issue by Bruce2jiang** [moiot/gravity#205]
How to deal with these three problem :
If the table structure A has increased the DDL operation of the column in the time period from T0 to T1, then when the binlog of the table A of the T0 time period is processed, the table structure obtained is the mirror of T1, and the column mismatch will occur. For example, the previous exception: column size is not match for table: xx , 12 vs 13

If the C1 column is added and the C2 column is deleted in T0~T1, the total number of columns obtained at this time is still the same as that of T0, but the corresponding column is misplaced.

If the DDL of the drop table occurs in T0~T1, there will be an exception that cannot be found when taking the table structure, and the entire binlog processing is blocked, such as not found [xx] in db

**Comment by Ryan-Git** [comment]
the complete solution would be #174, which haven't been implemented yet. for now, the solution is re-sync the whole table from scratch. 

BTW, ur cases are quite rare, only happens when the process **RESTARTS** between T0 and T1, or when several ddl on same table are processed almost simultaneously.

In our production env, this do happen between MySQL <--> TiDB as some DDL(that TiDB not support) will block the pipeline. We rarely see it between MySQL as the end2end latency is just several ten ms.

**Comment by Ryan-Git** [comment]
close due to inactivity. Further information available upon request.
