### ISSUE TITLE
MySQL foreign keys

### ISSUE THREAD

**Issue by MarkHaakman** [moiot/gravity#271]
Hi!

I just noticed that Gravity does not support MySQL foreign keys yet. My intention is to use Gravity (mysql to mysql) on tables with multiple foreign keys, so it does not work right now.

**Is there a way around this right now?** Otherwise, what should be changed or added in the code of Gravity to support foreign keys?

Thanks for your help.

**Comment by Ryan-Git** [comment]
if you're doing bounded one time syncing, disable foreign key constraint at related level(instance, table, etc) is the most convenient work around.

If you need real time replication and fk is satisfied in different transaction(insert parent row in one txn and insert child rows in another rather than all in one), set num of scheduler worker to 1 should work in low traffic.

Otherwise, it's quite a few change. It needs a new transaction aware scheduler and mysql output. Currently the `batch scheduler` is designed for row level parallelism and output for batch optimization within single table.

**Comment by MarkHaakman** [comment]
Thanks for your answer @Ryan-Git . Is it possible to let Gravity disable foreign key constraints automatically and enabling the constrains again when it is done? (By for example sending the `SET FOREIGN_KEY_CHECKS=0;` command)

I also have another question: Why is there chosen for a `REPLACE INTO` statement instead of `UPDATE`? Using an update statement would resolve the foreign key constraint issue right?

**Comment by Ryan-Git** [comment]
> Is it possible to let Gravity disable foreign key constraints automatically and enabling the constrains again when it is done? (By for example sending the SET FOREIGN_KEY_CHECKS=0; command)

Yes, we can do this at the start and end of batch mode. But for stream mode, this seems cancel the functionality foreign key provides.

> Why is there chosen for a REPLACE INTO statement instead of UPDATE?

Because with replace we can leverage the bulk replace grammar which gives better throughput in many cases.

> Using an update statement would resolve the foreign key constraint issue right?

No. Internally we dispatch changes by row rather than transaction. It's this schedule mode break the foreign key constraint.

**Comment by MarkHaakman** [comment]
Thank you for your insights!
